name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install pnpm and all workspace dependencies
        run: |
          npm install -g pnpm
          pnpm install --recursive   # 一次性安装根目录 + 所有子包依赖

      - name: Build Next.js app
        run: |
          cd apps/next-space
          pnpm build
          pnpm export  # 导出静态文件到 out 文件夹

      - name: Deploy to GitHub Pages
        run: |
          cd apps/next-space
          npx gh-pages -d out
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
